// Class include
#include "TRExFitter/Systematic.h"

// -------------------------------------------------------------------------------------------------
// Systematic

//_____________________________________________________________________________
//
Systematic::Systematic(const std::string& name,int type,double up,double down) :
    fName(name),
    fNuisanceParameter(name),
    fTitle(name),
    fCategory(""),
    fSubCategory("Uncategorised"),
    fStoredName(name),
    fType(type),
    fSmoothType(0),
    fPreSmoothing(false),
    fSampleSmoothing(false),
    fSymmetrisationType(HistoTools::NOSYMMETRIZATION),
    fReferenceSample(""),
    fKeepReferenceOverallVar(true),
    fReferenceSmoothing(""),
    fReferencePruning(""),
    fSubtractRefSampleVar(false),
    fOverallUp(up),
    fOverallDown(down),
    fScaleUp(1.),
    fScaleDown(1.),
    fHasUpVariation(true),
    fHasDownVariation(true),
    fIsFreeParameter(false),
    fIsCorrelated(true),
    fIsShapeOnly(false),
    fIsNormOnly(false),
    fNoPruning(false),
    fWeightUp(""),
    fWeightSufUp(""),
    fNtuplePathSufUp(""),
    fNtupleFileSufUp(""),
    fNtupleNameSufUp(""),
    fNtuplePathSufUpRefSample(""),
    fNtupleFileSufUpRefSample(""),
    fNtupleNameSufUpRefSample(""),
    fWeightDown(""),
    fWeightSufDown(""),
    fNtuplePathSufDown(""),
    fNtupleFileSufDown(""),
    fNtupleNameSufDown(""),
    fNtuplePathSufDownRefSample(""),
    fNtupleFileSufDownRefSample(""),
    fNtupleNameSufDownRefSample(""),
    fIgnoreWeight(""),
    fHistoPathSufUp(""),
    fHistoFileSufUp(""),
    fHistoNameSufUp(""),
    fHistoPathSufUpRefSample(""),
    fHistoFileSufUpRefSample(""),
    fHistoNameSufUpRefSample(""),
    fHistoPathSufDown(""),
    fHistoFileSufDown(""),
    fHistoNameSufDown(""),
    fHistoPathSufDownRefSample(""),
    fHistoFileSufDownRefSample(""),
    fHistoNameSufDownRefSample(""),
    fSampleUp(""),
    fSampleDown(""),
    fForceShape(HistoTools::FORCESHAPETYPE::NOSHAPE) {
}
